# DeathPosition Configuration

# Use {x} to show coordinat X! 
# Use {y} to show coordinat Y! 
# Use {z} to show coordinat Z! 

#Setting Here!
death-position-message: "§eYour death position on coordinates: §a{x} {y} {z}"
